name: FTP Deploy

on:
  push:
    branches:
      - test_app # Change this to your default branch if different

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Upload to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ # Local directory to upload, adjust as necessary
          protocol: ftp # Use 'sftp' if you need a secure connection
          git-ftp-args: --insecure # If you need to allow insecure connections, remove this if unnecessary
